project_name: casedev
version: 2

before:
  hooks:
    - mkdir -p completions
    - sh -c "go run ./cmd/casedev/main.go @completion bash > completions/casedev.bash"
    - sh -c "go run ./cmd/casedev/main.go @completion zsh > completions/casedev.zsh"
    - sh -c "go run ./cmd/casedev/main.go @completion fish > completions/casedev.fish"
    - sh -c "go run ./cmd/casedev/main.go @manpages -o man"

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/casedev/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

  - id: linux
    goos: [linux]
    goarch: ['386', arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: '{{ .ProjectName }}'
    main: ./cmd/casedev/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

  - id: windows
    goos: [windows]
    goarch: ['386', amd64, arm64]
    binary: '{{ .ProjectName }}'
    main: ./cmd/casedev/main.go
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'

archives:
  - id: linux-archive
    ids: [linux]
    name_template: '{{ .ProjectName }}_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [tar.gz]
    files:
      - completions/*
      - man/*/*
  - id: macos-archive
    ids: [macos]
    name_template: '{{ .ProjectName }}_{{ .Version }}_macos_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    files:
      - completions/*
      - man/*/*
  - id: windows-archive
    ids: [windows]
    name_template: '{{ .ProjectName }}_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [zip]
    files:
      - completions/*
      - man/*/*

snapshot:
  version_template: '{{ .Tag }}-next'

nfpms:
  - license: Apache-2.0
    maintainer: support@casemark.com
    bindir: /usr
    formats:
      - apk
      - deb
      - rpm
      - termux.deb
      - archlinux
    contents:
      - src: man/man1/*.1.gz
        dst: /usr/share/man/man1/
homebrew_casks:
  - name: casedev
    repository:
      owner: CaseMark
      name: homebrew-casedev
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://case.dev
    description: The official CLI for case.dev — manage legal AI resources from the terminal
    license: Apache-2.0
    binary: "casedev"
    completions:
      bash: "completions/casedev.bash"
      zsh: "completions/casedev.zsh"
      fish: "completions/casedev.fish"
    manpages:
    - man/man1/casedev.1.gz
